knife:
  production: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC
    username: root
    password: 123456
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.sdjusei.sdjulife.model.domain
  configuration:
    map-underscore-to-camel-case: true
